### ISSUE TITLE
Invalid Configuration for Read-Only Attribute

### ISSUE THREAD

**Issue by rfdrew** [cloudflare/terraform-provider-cloudflare#4915]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform -v
Terraform v1.10.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v5.0.0-rc1

### Affected resource(s)

cloudflare_account_token

### Terraform configuration files

```hcl
resource "cloudflare_account_token" "terraform" {
  provider = cloudflare.token_create
  account_id = data.cloudflare_account.example.id
  name = "Terraform"
  policies = [{
    effect = "allow"
    permission_groups = [
      {
        id = "3030687196b94b638145a3953da2b699",
        name = "Zone Settings Write"
      }
    ]
    resources = {
      "com.cloudflare.api.account.${data.cloudflare_account.example.id}" = "*"
    }
  }]
}
```

### Link to debug output

none

### Panic output

With "name" attribute
```
% terraform apply -target=cloudflare_account_token.terraform
╷
│ Error: Invalid Configuration for Read-Only Attribute
│ 
│   with cloudflare_account_token.terraform,
│   on cloudflare-account-tokens.tf line 1, in resource "cloudflare_account_token" "terraform":
│    1: resource "cloudflare_account_token" "terraform" {
│ 
│ Cannot set value for this attribute as the provider has marked it as read-only. Remove the configuration line setting the value.
│ 
│ Refer to the provider documentation or contact the provider developers for additional information about configurable and read-only attributes that are supported.
╵
╷
│ Error: Invalid Configuration for Read-Only Attribute
│ 
│   with cloudflare_account_token.terraform,
│   on cloudflare-account-tokens.tf line 4, in resource "cloudflare_account_token" "terraform":
│    4:   name = "Terraform"
│ 
│ Cannot set value for this attribute as the provider has marked it as read-only. Remove the configuration line setting the value.
│ 
│ Refer to the provider documentation or contact the provider developers for additional information about configurable and read-only attributes that are supported.
╵

```
Without "name" attribute
```
% terraform apply -target=cloudflare_account_token.terraform
╷
│ Error: Missing required argument
│ 
│   on cloudflare-account-tokens.tf line 1, in resource "cloudflare_account_token" "terraform":
│    1: resource "cloudflare_account_token" "terraform" {
│ 
│ The argument "name" is required, but no definition was found.
╵

```

### Expected output

Account token will be created

### Actual output

` Error: Invalid Configuration for Read-Only Attribute` or `Error: Missing required argument`

### Steps to reproduce

Use "name" attribute in "cloudflare_account_token" resource

**Comment by jacobbednarz** [comment]
the error here is misleading; it's not the first instance of the `name` attribute that is problematic. it's the `permission_group.name`. 

here is the full diagnostic (also why we ask for the TF_LOG output even for these types of issues)

```
[ERROR] provider.terraform-provider-cloudflare_v5.0.0: Response contains error diagnostic: tf_req_id=37d6a267-f114-51f1-574d-9d05e0bd230d tf_resource_type=cloudflare_account_token @caller=github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov6/internal/diag/diagnostics.go:58 @module=sdk.proto
  diagnostic_detail=
  | Cannot set value for this attribute as the provider has marked it as read-only. Remove the configuration line setting the value.
  |
  | Refer to the provider documentation or contact the provider developers for additional information about configurable and read-only attributes that are supported.
   diagnostic_summary="Invalid Configuration for Read-Only Attribute" tf_proto_version=6.7 diagnostic_attribute="AttributeName(\"policies\").ElementKeyInt(0).AttributeName(\"permission_groups\").ElementKeyInt(0).AttributeName(\"name\")" diagnostic_severity=ERROR tf_provider_addr=registry.terraform.io/cloudflare/cloudflare tf_rpc=ValidateResourceConfig timestamp="2025-02-06T08:04:33.425+1100"
2025-02-06T08:04:33.426+1100 [ERROR] vertex "cloudflare_account_token.terraform" error: Invalid Configuration for Read-Only Attribute
```

the schema for this definitely is conflicting

```yaml
iam_permission_group:
  description: A named group of permissions that map to a group of operations against resources.
  properties:
      id:
          description: Identifier of the group.
          example: 6d7f2f5f5b1d4a0e9081fdc98d432fd1
          readOnly: true
          type: string
      meta:
          description: Attributes associated to the permission group.
          example:
              label: load_balancer_admin
              scopes: com.cloudflare.api.account
          properties:
              key:
                  type: string
              value:
                  type: string
          type: object
      name:
          description: Name of the group.
          example: Load Balancer
          readOnly: true
          type: string
  required:
    - id
```

will chat with the IAM folks on getting this triaged.
