### ISSUE TITLE
`cloudflare_zero_trust_gateway_logging` (v5.2.0): Objects in `settings_by_rule_type` undefined (`dns`, `http`, `l4`)

### ISSUE THREAD

**Issue by josip-stanic** [cloudflare/terraform-provider-cloudflare#5366]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.11.2
on linux_amd64

 ```
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "= 5.2.0"
    }
  }
}
 ```

### Affected resource(s)

`cloudflare_zero_trust_gateway_logging `

### Terraform configuration files

```hcl
resource "cloudflare_zero_trust_gateway_logging" "example" {
  account_id = var.cloudflare_account_id
  redact_pii = true
  settings_by_rule_type = {
    dns = {
    }
    http = {
    }
    l4 = {
    }
  }
}
```

### Link to debug output

NA

### Panic output

Does not panic or crash

### Expected output

In v4 we were able to specify logging settings in Gateway via resource  `cloudflare_zero_trust_gateway_settings`, like:
 ```
# v4
resource "cloudflare_zero_trust_gateway_settings" "example" {
  account_id           = var.cloudflare_account_id
  activity_log_enabled = false
 ...
  logging {
    redact_pii = false

    settings_by_rule_type {
      dns {
        log_all    = true
        log_blocks = false
      }
      http {
        log_all    = true
        log_blocks = false
      }
      l4 {
        log_all    = true
        log_blocks = false
      }
    }
  }
}
 ```

### Actual output

As I understand in v5 this has been segregated into resource `cloudflare_zero_trust_gateway_logging`, when trying to plan the resource as it's written in the provider docs ([here](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zero_trust_gateway_logging)) I get following error:

Error: Incorrect attribute value type
on zero_trust.tf line 27, in resource "cloudflare_zero_trust_gateway_logging" "example":
  settings_by_rule_type = {
    dns = {
    }
    http = {
    }
    l4 = {
    }
  }
Inappropriate value for attribute "settings_by_rule_type": attribute "dns": string required.

I believe this stems from the `openapi.yaml` not including properties of the objects and the rest of the chain not generating this correctly:
 ```
#https://raw.githubusercontent.com/cloudflare/api-schemas/refs/heads/main/openapi.yaml
...
        zero-trust-gateway_gateway-account-logging-settings:
            properties:
                redact_pii:
                    description: 'Redact personally identifiable information from activity logging (PII fields are: source IP, user email, user ID, device ID, URL, referrer, user agent).'
                    example: true
                    type: boolean
                settings_by_rule_type:
                    description: Logging settings by rule type.
                    properties:
                        dns:
                            description: Logging settings for DNS firewall.
                            type: object
                        http:
                            description: Logging settings for HTTP/HTTPS firewall.
                            type: object
                        l4:
                            description: Logging settings for Network firewall.
                            type: object
                    type: object
            type: object
...
 ```

Including ` log_[all|block]    = block` as in v4 in the objects does not work either, like:
 ```
resource "cloudflare_zero_trust_gateway_logging" "example" {
  account_id = var.cloudflare_account_id
  redact_pii = true
  settings_by_rule_type = {
    dns = {
        log_all    = true
        log_blocks = true
    }
    http = {
        log_all    = true
        log_blocks = true
    }
    l4 = {
        log_all    = true
        log_blocks = true
    }
  }
}
 ```

Maybe something that was missed during the rewrite? Can you provide guidance on how the Gateway logging is configured correctly?

### Steps to reproduce

Trying to configure Gateway Logging as documented in the [provider docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zero_trust_gateway_logging).

### References

- https://raw.githubusercontent.com/cloudflare/api-schemas/refs/heads/main/openapi.yaml
- https://github.com/cloudflare/cloudflare-go/blob/main/zero_trust/gatewaylogging.go#L138-L145
